### ISSUE TITLE
IndexError: kthvalue(): Expected reduction dim 0 to have non-zero size.

### ISSUE THREAD

**Issue by gafaua** [EIDOSLAB/torchstain#54] opened 2023-10-20 21:23 UTC
**Describe the bug**
I use Macenko Normalizer as part of an augmentation pipeline in a PyTorch environment. It works fine almost everytime, but once in a while (especially when working with small images below 512x512), it will sometimes throw the error

```IndexError: kthvalue(): Expected reduction dim 0 to have non-zero size.```

and I have no idea why.

**To Reproduce**
I honestly couldn't say how to reproduce the bug, it is quite very rare, but when it happens it crashes the training process. My intuition would be that it can happen more on small images where there isn't a lot of tissue (white space, black marks, etc), but I don't know for sure.

**Expected behavior**
It crashes and throws the above error.

**Logs**
```
Original Traceback (most recent call last):
  File "/home/travail/anaconda3/envs/placenta/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/travail/anaconda3/envs/placenta/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/travail/anaconda3/envs/placenta/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/travail/repos/plac/lib/wsi_analysis/wsi_dataset.py", line 60, in __getitem__
    img = self.transforms(img)
  File "/home/travail/repos/plac/lib/utils/simsiam.py", line 20, in __call__
    k = self.base_transform(x)
  File "/home/travail/anaconda3/envs/pla/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/home/travail/anaconda3/envs/pla/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/travail/repos/plac/lib/datasets/macenko.py", line 13, in forward
    x, _, _ = self.norm.normalize(x*255, stains=False)
  File "/home/travail/anaconda3/envs/pla/lib/python3.10/site-packages/torchstain/torch/normalizers/macenko.py", line 105, in normalize
    HE, C, maxC = self.__compute_matrices(I, Io, alpha, beta)
  File "/home/travail/anaconda3/envs/pla/lib/python3.10/site-packages/torchstain/torch/normalizers/macenko.py", line 68, in __compute_matrices
    HE = self.__find_HE(ODhat, eigvecs, alpha)
  File "/home/travail/anaconda3/envs/pla/lib/python3.10/site-packages/torchstain/torch/normalizers/macenko.py", line 39, in __find_HE
    minPhi = percentile(phi, alpha)
  File "/home/travail/anaconda3/envs/pla/lib/python3.10/site-packages/torchstain/torch/utils/percentile.py", line 24, in percentile
    return t.view(-1).kthvalue(k).values
IndexError: kthvalue(): Expected reduction dim 0 to have non-zero size.
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Fedora
 - Version 36

**Comment by andreped** [comment] 2023-10-20 21:47
Duplicate of issue https://github.com/EIDOSLAB/torchstain/issues/1.

I believe that issue should contain all the information you need to handle this problem.
Let me know if you experience any issues further :]

**Comment by gafaua** [comment] 2023-10-21 17:41
Oh I missed that one, thank you!

**Comment by andreped** [comment] 2023-10-21 17:55
As this issue has been previously resolved, I am closing this issue. If you experience any future issues, feel free to ask :]

**Closed by andreped** 2023-10-21 17:55 UTC
